/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Radio_Box_Frame extends javax.swing.JFrame {


    /**
     * Creates new form Radio_Box_Frame
     */
    public Radio_Box_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonBird = new javax.swing.JRadioButton();
        jRadioButtonCat = new javax.swing.JRadioButton();
        jRadioButtonDog = new javax.swing.JRadioButton();
        jRadioButtonRabbit = new javax.swing.JRadioButton();
        jRadioButtonPig = new javax.swing.JRadioButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        buttonGroup1.add(jRadioButtonBird);
        jRadioButtonBird.setText("Bird");
        jRadioButtonBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBirdActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCat);
        jRadioButtonCat.setText("Cat");
        jRadioButtonCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCatActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDog);
        jRadioButtonDog.setText("Dog");
        jRadioButtonDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDogActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRabbit);
        jRadioButtonRabbit.setText("Rabbit");
        jRadioButtonRabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRabbitActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPig);
        jRadioButtonPig.setText("Pig");
        jRadioButtonPig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPig)
                    .addComponent(jRadioButtonRabbit)
                    .addComponent(jRadioButtonDog)
                    .addComponent(jRadioButtonCat)
                    .addComponent(jRadioButtonBird))
                .addGap(112, 112, 112)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonBird)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButtonCat)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButtonDog)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonRabbit)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonPig)))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBirdActionPerformed
        // TODO add your handling code here:
        displayPet("Bird", "/bird.jpeg");
    }//GEN-LAST:event_jRadioButtonBirdActionPerformed

    private void jRadioButtonCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCatActionPerformed
        // TODO add your handling code here:
        displayPet("Cat", "/cat.jpeg");
    }//GEN-LAST:event_jRadioButtonCatActionPerformed

    private void jRadioButtonDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDogActionPerformed
        // TODO add your handling code here:
        displayPet("Dog", "/dog.jpeg");
    }//GEN-LAST:event_jRadioButtonDogActionPerformed

    private void jRadioButtonRabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRabbitActionPerformed
        // TODO add your handling code here:
        displayPet("Rabbit", "/rabbit.jpeg");
    }//GEN-LAST:event_jRadioButtonRabbitActionPerformed

    private void jRadioButtonPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPigActionPerformed
        // TODO add your handling code here:
        displayPet("Pig", "/pig.jpeg");
    }//GEN-LAST:event_jRadioButtonPigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radio_Box_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radio_Box_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radio_Box_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radio_Box_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radio_Box_Frame().setVisible(true);
            }
        });
    }

    private void displayPet(String petName, String imagePath) {
    ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
    imageLabel.setIcon(icon);
    JOptionPane.showMessageDialog(this, "You selected: " + petName);
}

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JRadioButton jRadioButtonBird;
    private javax.swing.JRadioButton jRadioButtonCat;
    private javax.swing.JRadioButton jRadioButtonDog;
    private javax.swing.JRadioButton jRadioButtonPig;
    private javax.swing.JRadioButton jRadioButtonRabbit;
    // End of variables declaration//GEN-END:variables
}
